### ISSUE TITLE
`rpc_method` is not present in run_results.json

### ISSUE THREAD

**Issue by rsov** [chasleslr/dbt-junitxml#5]
Looks like the format was changed and it was renamed to `which`

Currently fails with:
```
dbt@ubuntu:/usr/app/dbt$ dbt-junitxml parse target/run_results.json test-results.xml
Traceback (most recent call last):
  File "/home/dbt/.local/lib/python3.11/site-packages/dbt_junitxml/main.py", line 30, in parse
    rpc_method = run_result["args"]["rpc_method"]
                 ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'rpc_method'
```

**Comment by SOVALINUX** [comment]
Hi @rsov  
I've fixed this issue in my fork https://github.com/SOVALINUX/dbt-junitxml/releases/tag/0.2.0   
We use it in production for a long time, however I recommend you to stick to some specific version and upgrade manually, since latest version might occasionally have new changes that may not fit your business.  
By the way, I've integrated our DBT tests into https://reportportal.io/ and I use this lib to let my team handle Test Launch Management there

**Comment by rsov** [comment]
@SOVALINUX Dziękuję my friend. You should make an official release, it's a very useful tool and this project seems to be very quiet

**Comment by SOVALINUX** [comment]
Hey @rsov   
Thanks! Spent some time to update the README and describe what we've built. However I didn't took over the original package name and didn't yet introduced the alternative name :)  
Anyway, I hope it may help you to move forward with your case  
https://github.com/SOVALINUX/dbt-junitxml

**Comment by rsov** [comment]
Legend 🙌
